In [1]:
import numpy as np

# Reshape

In [2]:
x = np.random.randn(4,5)

In [3]:
x

array([[-0.74883746,  0.16274846, -1.76012881,  1.88833908, -1.02526542],
       [-1.09144675,  0.43310488, -1.20926256,  0.776008  ,  0.21583666],
       [-0.21421056, -1.01383576,  0.73187892,  1.38678603, -0.01232643],
       [ 0.30385848,  0.31830258,  0.16818237,  0.45954083,  0.02225575]])

In [4]:
x.reshape((2,2,5))

array([[[-0.74883746,  0.16274846, -1.76012881,  1.88833908,
         -1.02526542],
        [-1.09144675,  0.43310488, -1.20926256,  0.776008  ,
          0.21583666]],

       [[-0.21421056, -1.01383576,  0.73187892,  1.38678603,
         -0.01232643],
        [ 0.30385848,  0.31830258,  0.16818237,  0.45954083,
          0.02225575]]])

In [5]:
x.reshape((2,2,5),order='F')

array([[[-0.74883746,  0.16274846, -1.76012881,  1.88833908,
         -1.02526542],
        [-0.21421056, -1.01383576,  0.73187892,  1.38678603,
         -0.01232643]],

       [[-1.09144675,  0.43310488, -1.20926256,  0.776008  ,
          0.21583666],
        [ 0.30385848,  0.31830258,  0.16818237,  0.45954083,
          0.02225575]]])

In [6]:
x.reshape((2,2,-1))

array([[[-0.74883746,  0.16274846, -1.76012881,  1.88833908,
         -1.02526542],
        [-1.09144675,  0.43310488, -1.20926256,  0.776008  ,
          0.21583666]],

       [[-0.21421056, -1.01383576,  0.73187892,  1.38678603,
         -0.01232643],
        [ 0.30385848,  0.31830258,  0.16818237,  0.45954083,
          0.02225575]]])

In [7]:
x

array([[-0.74883746,  0.16274846, -1.76012881,  1.88833908, -1.02526542],
       [-1.09144675,  0.43310488, -1.20926256,  0.776008  ,  0.21583666],
       [-0.21421056, -1.01383576,  0.73187892,  1.38678603, -0.01232643],
       [ 0.30385848,  0.31830258,  0.16818237,  0.45954083,  0.02225575]])

In [8]:
x.ravel()

array([-0.74883746,  0.16274846, -1.76012881,  1.88833908, -1.02526542,
       -1.09144675,  0.43310488, -1.20926256,  0.776008  ,  0.21583666,
       -0.21421056, -1.01383576,  0.73187892,  1.38678603, -0.01232643,
        0.30385848,  0.31830258,  0.16818237,  0.45954083,  0.02225575])

In [10]:
x.flatten()

array([-0.74883746,  0.16274846, -1.76012881,  1.88833908, -1.02526542,
       -1.09144675,  0.43310488, -1.20926256,  0.776008  ,  0.21583666,
       -0.21421056, -1.01383576,  0.73187892,  1.38678603, -0.01232643,
        0.30385848,  0.31830258,  0.16818237,  0.45954083,  0.02225575])

# Concatenate

In [6]:
x = [[1,3,5],[7,9,0]]

In [7]:
arr1 = np.array(x)

In [8]:
y = [[11,13,15],[17,19,10]]

In [9]:
arr2 = np.array(y)

In [10]:
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [11]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [12]:
np.vstack((arr1,arr2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [13]:
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

# Split

In [2]:
d = [4,8,5,7,1,9,0];

In [3]:
np.array(d)

array([4, 8, 5, 7, 1, 9, 0])

In [4]:
np.split(d, [4,6])

[array([4, 8, 5, 7]), array([1, 9]), array([0])]

In [7]:
y = [[4,8,5,7,1,9,0],[14,18,15,17,11,19,10]]

In [8]:
z = np.array(y)

In [9]:
np.split(z, [3,5], axis=1)

[array([[ 4,  8,  5],
        [14, 18, 15]]),
 array([[ 7,  1],
        [17, 11]]),
 array([[ 9,  0],
        [19, 10]])]

# Repeat & Tile

In [24]:
d = np.array([5,6,1,8,0,2]);
d

array([5, 6, 1, 8, 0, 2])

In [25]:
rep = np.repeat(d,2);
rep

array([5, 5, 6, 6, 1, 1, 8, 8, 0, 0, 2, 2])

In [26]:
np.tile(d,2)

array([5, 6, 1, 8, 0, 2, 5, 6, 1, 8, 0, 2])

# Learn Broadcasting from Book (if you want)