In [1]:
import numpy as np

In [2]:
a = np.random.randn((10)) #creating random array of 10 elements

In [3]:
b = np.random.randn((10))

In [4]:
a

array([-1.93437244, -0.84395655, -0.09281901, -1.39512466, -0.94318852,
       -0.4584031 , -0.6978441 ,  0.36838306,  0.91194295, -0.16662573])

In [5]:
b

array([-0.01154523,  0.82796798,  1.64133831,  0.35015677,  1.77569173,
       -0.19816917,  1.00140738,  2.41872751,  0.46580632, -0.59174114])

In [6]:
a + b #adding a and b > we can make all type of calculations on them case is shape of both arrays must be save 

array([-1.94591768, -0.01598857,  1.5485193 , -1.04496789,  0.83250321,
       -0.65657227,  0.30356328,  2.78711057,  1.37774927, -0.75836686])

In [7]:
2*a

array([-3.86874489, -1.68791309, -0.18563803, -2.79024932, -1.88637704,
       -0.9168062 , -1.3956882 ,  0.73676612,  1.8238859 , -0.33325145])

In [8]:
1/a

array([ -0.51696353,  -1.18489513, -10.77365471,  -0.71678183,
        -1.06023343,  -2.18148613,  -1.43298481,   2.71456563,
         1.09655982,  -6.00147419])

In [9]:
a>0 #checking positive numbers in an array it gives boolean array showing condition matched or not

array([False, False, False, False, False, False, False,  True,  True,
       False])

In [10]:
a[a>0] #it gives all values that matches given condition

array([0.36838306, 0.91194295])