In [1]:
import numpy as np

In [3]:
x = np.array([10,9,8,6,11])

In [4]:
# sqrt() function gives Square Root of every Element
np.sqrt(x)

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [5]:
# power() function gives power of every element as defined in second argument 2 power of x
np.power(x,2)

array([100,  81,  64,  36, 121], dtype=int32)

In [6]:
y = [7,1,2,3,-1]

In [7]:
# maximum() function gives array of maximum values from comparing both arrays indexes wise
np.maximum(x,y)

array([10,  9,  8,  6, 11])