In [1]:
import numpy as np

In [3]:
x = np.array([1,7,9,8,5])

In [4]:
x[4]

5

In [5]:
x[x>5] # Boolean Indexing

array([7, 9, 8])

In [7]:
# Fancy Indexing:
x[[2,1]]

array([9, 7])

In [8]:
x = np.random.randn(10,10)

In [9]:
x

array([[-0.15907319, -0.44816054,  0.65098294,  0.56216458, -0.74035725,
        -0.68611004, -0.19963404,  1.65251159, -1.79639426,  0.40575127],
       [ 1.80658306, -0.14025036,  1.24273419,  0.37763376,  0.09902116,
        -0.25991218,  0.28658692,  0.2619428 ,  1.32805939,  0.36546355],
       [ 1.53529008,  0.22951675, -0.59502588, -0.39180586, -0.34869145,
        -1.77631883, -1.99297237, -1.38544502,  0.82976782,  0.26254516],
       [ 2.01533432,  0.3520902 , -0.21348265,  0.13839347,  1.25165463,
        -0.8881975 , -1.0138745 ,  0.00380293,  0.54586213, -0.42016201],
       [-0.82356987, -1.37083309, -0.14507034,  0.03333345,  1.66188782,
         0.42104242,  1.05761155, -0.37358383,  0.47448998, -0.6683557 ],
       [-0.05938989,  0.71333177, -0.97314929, -1.36791907,  0.52289028,
        -0.39032592,  1.74568605, -0.01302293,  0.40318256,  0.85308845],
       [-0.28733916,  0.71102939,  0.89354944, -0.90828457,  0.84730228,
        -0.47428949,  0.34423238, -0.93609251

In [10]:
x[0]

array([-0.15907319, -0.44816054,  0.65098294,  0.56216458, -0.74035725,
       -0.68611004, -0.19963404,  1.65251159, -1.79639426,  0.40575127])

In [11]:
x[0][4]

-0.7403572514043004

In [12]:
x[1:10:2,::] # Syntax Explanation: [starting_index:ending_index:steps:columns_to_get] & :: operator used to skip any value or work same like all/everything without specifiyng condition/value

array([[ 1.80658306, -0.14025036,  1.24273419,  0.37763376,  0.09902116,
        -0.25991218,  0.28658692,  0.2619428 ,  1.32805939,  0.36546355],
       [ 2.01533432,  0.3520902 , -0.21348265,  0.13839347,  1.25165463,
        -0.8881975 , -1.0138745 ,  0.00380293,  0.54586213, -0.42016201],
       [-0.05938989,  0.71333177, -0.97314929, -1.36791907,  0.52289028,
        -0.39032592,  1.74568605, -0.01302293,  0.40318256,  0.85308845],
       [ 0.25342334, -0.11833968, -0.13600101,  1.4642096 , -1.38559692,
        -0.86531943, -0.88450112, -1.4989006 ,  1.77691423,  1.12320183],
       [-1.03217792, -0.60881846, -0.17251123, -0.5215804 ,  0.96580565,
         1.85950848,  1.7293671 ,  0.73507955,  0.37223927, -0.87200178]])

In [13]:
x[::,0:4]

array([[-0.15907319, -0.44816054,  0.65098294,  0.56216458],
       [ 1.80658306, -0.14025036,  1.24273419,  0.37763376],
       [ 1.53529008,  0.22951675, -0.59502588, -0.39180586],
       [ 2.01533432,  0.3520902 , -0.21348265,  0.13839347],
       [-0.82356987, -1.37083309, -0.14507034,  0.03333345],
       [-0.05938989,  0.71333177, -0.97314929, -1.36791907],
       [-0.28733916,  0.71102939,  0.89354944, -0.90828457],
       [ 0.25342334, -0.11833968, -0.13600101,  1.4642096 ],
       [ 1.02578035, -0.59291877, -0.73393266, -0.41114056],
       [-1.03217792, -0.60881846, -0.17251123, -0.5215804 ]])

In [14]:
x = np.ones((5,5))

In [15]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
x[1:-1,1:-1] = 0

In [17]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Assignment ChessBoard Pattern