In [1]:
import numpy as np

In [2]:
x = np.array([10,9,7,10,7])

In [4]:
# gives average/mean of array
x.mean()

8.6

In [5]:
# gives cumulative sum of every element in an array
x.cumsum()

array([10, 19, 26, 36, 43])

In [7]:
# gives cumulative Product of every element in an array
x.cumprod()

array([   10,    90,   630,  6300, 44100])

In [8]:
y = x > 6

In [9]:
y

array([ True,  True,  True,  True,  True])

In [10]:
# gives count of elements match specified condition which we give above
y.sum()

5

In [11]:
# gives true if any element match specified condition which we give above
y.any()

True

In [12]:
# gives true if all elements match specified condition which we give above
y.all()

True

In [13]:
y = x > 7

In [14]:
y

array([ True,  True, False,  True, False])

In [15]:
y.sum()

3

In [16]:
y.any()

True

In [17]:
y.all()

False

In [18]:
x.sort()

In [19]:
x

array([ 7,  7,  9, 10, 10])

In [20]:
np.unique(x)

array([ 7,  9, 10])